name: Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm install

      - name: Install dependencies (Backend)
        working-directory: backend
        run: npm install

      - name: Build Angular app
        working-directory: frontend
        run: npm run build

      - name: Start Backend server
        working-directory: backend
        run: npm run start &
        env:
          PGURI: ${{ secrets.PGURI }}
          PORT: 3000

      - name: Wait for Backend server
        run: npx wait-on http://localhost:3000

      - name: Start Angular server
        working-directory: frontend
        run: npm run start -- --port 4200 &
        env:
          CI: true

      - name: Wait for Angular server
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        working-directory: frontend
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: "http://localhost:4200,http://localhost:3000"
          wait-on-timeout: 120
